umbraco/OurUmbraco

- OurUmbraco.Site/Views/MacroPartials/Projects/ProjectDetails.cshtml
Amended the contributors names & links (on the project detail page).
Names are linked to member profiles and comma-separated.
> OUR-147 Project contributors - missing links and spacing

- OurUmbraco.Site/Views/MacroPartials/Projects/ProjectDetails.cshtml
Corrected the package uploader's name.
> OUR-148 Project releases - displayed owner's name, instead of uploader.

- OurUmbraco.Client/src/scss/pages/_release.scss
Added font-family property to .markdown-syntax anchor tags
> Fix: OUR-304

- OurUmbraco.Site/Views/MacroPartials/Projects/ProjectDetails.cshtml
This is a quick fix for OUR-318, using a `pluralize()` helper. Not sure if there's a "general" place to put said helper - let me know if it's preferred to be in a specific file.
> Correctly pluralize "votes", using a helper

- OurUmbraco.Client/src/scss/elements/_package-detail.scss
Add styles for the `.smiley` states that were actual icons in the old site, e.g.:
- **untested**
- **superUnhappy**
- **unhappy**
- **neutral**
- **happy**
- **joyous**
Decided against the checkmark on *joyous* (as depicted in the [initial mockup][1]), after testing some scenarios of various combinations of states. They were a bit noisy :)
A **100%** compatible version gets bold-faced which seems to do the job.
[1]: http://issues.umbraco.org/issue/OUR-276?replyTo=67-22325#viewimage=project-compatibility-with-colors.png%3Ffile%3D64-2837%26v%3D0%26c%3Dtrue%26rw%3D918%26rh%3D724%26u%3D1435702794207
> OUR-276 - Colorize Project Compatibility

- OurUmbraco.Client/src/scss/elements/_utilities.scss
- OurUmbraco.Site/Views/MacroPartials/Forum/Thread.cshtml
Fix: Our-316. I have added the buttons for delete / follow thread and go directly to solution in the bottom of the thread. So if it´s a long thread with many replies, you do have to go to the top.
http://issues.umbraco.org/issue/OUR-316
> Our-316: Fix make it easier to follow a forum thread

- OurUmbraco.Client/src/scss/elements/_footer.scss
The text in the footer are being cut off on mobiles iPhone 4, 5 and 6
http://issues.umbraco.org/issue/OUR-341
> OUR-341 Fixed cutting fotter on smartphone 

- OurUmbraco.Client/src/scss/elements/_packages.scss
For some packages in the package list (here seen for popular projects) the version label are not all right aligned in same way.
http://issues.umbraco.org/issue/OUR-345
> OUR-345 Fix for version label so it always align right

- OurUmbraco.Site/Views/MacroPartials/Forum/LatestActivity.cshtml
http://issues.umbraco.org/issue/OUR-387
Added the "solved" class on the latestactivity forum-threads.
For some reasons, i did´nt get the /assets/css/style.min.css when i
cloned the repository, and i could´nt find it in
https://github.com/umbraco/OurUmbraco/tree/master/OurUmbraco.Site
either.
This css needs to be added to style.min.css for the threads to be green:
.forum .forum-thread.solved {
background: rgba(163, 219, 120, 0.23) none repeat scroll 0 0;
border: 2px solid rgba(163, 219, 120, 0.66);
}
> OUR-387 Solved "green color" not showing on startpage of Our

- OurUmbraco.Site/usercontrols/Deli/Package/Steps/Files.ascx
- OurUmbraco/MarketPlace/Providers/MediaProvider.cs
- OurUmbraco/Project/usercontrols/Deli/Package/Steps/Files.ascx
When a package is uploaded to the Our Umbraco repository, we extract the "package.xml" manifest to detect the required (minimum) Umbraco version number.
This task is part of [U4-8156](http://issues.umbraco.org/issue/U4-8156), at CGRT16
> Extracts package's required Umbraco version metadata

- OurUmbraco.Client/gulpfile.js
- OurUmbraco.Client/package.json
- OurUmbraco.Client/src/scss/elements/_alertbar.scss
- OurUmbraco.Client/src/scss/elements/_buttons.scss
- OurUmbraco.Client/src/scss/pages/_release.scss
- OurUmbraco.Client/src/scss/style.scss
- OurUmbraco.Client/src/scss/utilities/_flexbox.scss
- OurUmbraco.Site/masterpages/Release.master
I did some basic cleanup of classes and deleted unused styles along with the changes of the call to action for downloading a release. I also updated some packages and commented out the Combine Media Queries as it seems broken at the moment. Added utility file to support Flexbox.
Most `scss` files is cleanup or changes to . https://github.com/umbraco/OurUmbraco/commit/7ffb0286e3a8ec21f1a3f268ea7bc58143bf279e is where the magic happens.
> OUR-404 Update release pages to have a far more prominent call to action for download and install instructions

- OurUmbraco.Site/Views/RoadMap.cshtml
Very small fix which will allow the release description to be displayed instead of `release.releaseDescription`.
> Fixed typo on Roadmap.cshtml preventing ReleaseDescription from being displayed

- OurUmbraco.Site/Views/Master.cshtml
Preventing zoom is bad for accessibility as you cannot zoom into the website on mobile viewports. 
See http://alwaystwisted.com/articles/2013-01-10-dont-do-this-in-responsive-web-development for more information.
> Remove viewport meta properties preventing zoom

- OurUmbraco.Client/src/scss/elements/_packages.scss
- OurUmbraco.Client/src/scss/sections/_forum.scss
- OurUmbraco.Site/Views/Partials/Projects/ListProjects.cshtml
Fixed a couple things:
- Doubled the image size on the package listing and set it smaller with the CSS so it displays nicely for retina
- Removed the border-radius on profile pages for package listings so the icons are consistent
> Fixes issue #OUR-449.

- OurUmbraco.Site/Views/Partials/Home/GitHubContributors.cshtml
- OurUmbraco/Community/Controllers/GitHubContributorController.cs
- OurUmbraco/Community/GitHub/Controllers/GitHubContributorController.cs
- OurUmbraco/Community/GitHub/GitHubRepository.cs
- OurUmbraco/Community/GitHub/GitHubService.cs
- OurUmbraco/Community/GitHub/Models/Cached/GitHubCachedGlobalContributorModel.cs
- OurUmbraco/Community/GitHub/Models/GitHubContributorsModel.cs
- OurUmbraco/Community/GitHub/Models/GitHubContributorsResult.cs
- OurUmbraco/Community/GitHub/Models/GitHubGlobalContributorModel.cs
- OurUmbraco/Community/GitHub/Models/GithubContributorModel.cs
- OurUmbraco/Community/GitHub/Models/IGitHubContributorModel.cs
- OurUmbraco/Community/GitHub/Models/IGitHubContributorsModel.cs
- OurUmbraco/NotificationsCore/Notifications/ScheduleHangfireJobs.cs
- OurUmbraco/Our/GoogleOAuth/UmbracoStandardOwinStartup.cs
- OurUmbraco/OurUmbraco.csproj
This is still work in progress, so it's just to put it up here for any comments.
I haven't yet had the time to test the new logic that thoroughly when integrated with Our Umbraco, but the `GitHubService` class seems to work like it should. I will do some more testing, but you can now get the overall list of contributors like this (the parameter is the amount of retries, where `3` seems to be a fitting number):
```C#
GitHubService service = new GitHubService();
GitHubContributorsResult result = service.GetOverallContributors(3);
```
The `GetOverallContributors` also sorts the contributors a bit better - eg. if two users have the same amount of commits, but one has more additions than the other. So the one with the highest amount of additions is shown first. I'm also sorting by deletions …
> Updated the implementation for GitHub contributors

- OurUmbraco.Client/src/scss/sections/_contributors.scss
- OurUmbraco.Site/OurUmbraco.Site.csproj
- OurUmbraco.Site/Views/Partials/Community/Home.cshtml
- OurUmbraco.Site/Views/Partials/Community/Scripts.cshtml
- OurUmbraco.Site/Views/Partials/Home/GitHubContributors.cshtml
- OurUmbraco.Site/config/imageprocessor/security.config
- OurUmbraco.Site/packages.config
- OurUmbraco/OurUmbraco.csproj
- OurUmbraco/packages.config
Issue: http://issues.umbraco.org/issue/OUR-462
I have optimized the number of github contributors per row depending on different breakpoints.
Furthermore the white background is also aligned vertically with the other in e.g. forum posts and center the avatars, which I think look better e.g. when there is only two elements on last row.
**Before**
**After**
**Before**
**After**
It also fix these issues on mobile.
Same width of the white background as for forum posts, meetups etc.
Init number of github contributors fit to fill the row.
The smaller avatar in screenshot above is because the original image is too small for retina screens - the original size is only 200x200px https://avatars3.githubusercontent.com/u/1769475
Alternatively it can use ImageProcessor to handle size of the image, …
> Optimize github contributors for different breakpoints on frontpage

- OurUmbraco.Client/src/scss/elements/_sidebar.scss
- OurUmbraco.Site/Views/Projects.cshtml
Issue: http://issues.umbraco.org/issue/OUR-460
After upgradering jQuery version from 1.7.2 to 1.9.1, because Fancybox v3 requires jQuery 1.9+, it seems to break the project filter functionality due the way to select elements `jQuery(htmlString)` versus `jQuery(selectorString)`
https://stackoverflow.com/a/23960371
https://github.com/nathanvda/cocoon/issues/127
It seems to happen, where there is no querystring, where the `getUrlVars` function on this page was returning undefined. I have modified it to return an empty array instead.
Currently the filter function works if querystring contains any values, e.g. `?version=7` or just `?test=1` (which doesn't return the console error).
> Fix issues with filtering projects/packages

- OurUmbraco.Site/Views/Partials/Projects/ProjectDetails.cshtml
It turns out that I failed to fix this in #41 - I had only fixed it for the "Source code" tab, (doh!)
This now fixes it for each of the downloads tabs.
> OUR-148 Project releases - displayed owner's name, instead of uploader

- OurUmbraco/Our/CustomHandlers/ProjectIndexer.cs
- OurUmbraco/Our/Examine/DateRangeSearchFilter.cs
- OurUmbraco/Our/Examine/OurSearcher.cs
- OurUmbraco/Our/Examine/ProjectNodeIndexDataService.cs
- OurUmbraco/Our/Examine/ProjectPopularityPoints.cs
- OurUmbraco/Our/Utils.cs
- OurUmbraco/OurUmbraco.csproj
- OurUmbraco/Project/ProjectExtensions.cs
- OurUmbraco/Repository/Services/PackageRepositoryService.cs
- OurUmbraco/Wiki/BusinessLogic/WikiFile.cs
- OurUmbraco/Wiki/Models/MonthlyProjectDownloads.cs
popularity takes into account
// - download count in a recent timeframe - since old downloads should count for less
// - votes
// - recently updated            
// - works on Cloud
// - has a forum
// - has source code link
// - open for collab / has collaborators
TODO: 
// - works on latest umbraco versions            
Each of those items then has a weighting which can be adjusted. The download counts and recently updated also have their own aglorithms for creating a numerical value to score against.
This yields much better results for popularity
> Popular packages calculation updates

- OurUmbraco.Site/Views/Partials/Releases/ReleasesDropdown.cshtml
I noticed that versions during comparison on https://our.umbraco.org/contribute/releases/compare page are not passed as a query string parameters and the result cannot be easily shared between people. 
I thought the whole feature is missing, but I noticed everything is there, but the wrong form method was causing those params to dissapear. 
Changing it from POST to GET fixed the problem. Hope it will help others too :)
> Form method changed to pass form values as querystring params

- OurUmbraco/Our/Controllers/ProjectController.cs
Fixes
- [OUR-391 Can't Save Bug Tracking URL for Umbraco Package](http://issues.umbraco.org/issue/OUR-391)
- [OUR-339 Package Bug tracking URL is not persisted](http://issues.umbraco.org/issue/OUR-339)
- [OUR-357 Project Url value does not save](http://issues.umbraco.org/issue/OUR-357)
> Edit Project: Fixes the save "Project URL" and "Bug Tracking URL" fields

- OurUmbraco.Site/config/IISRewriteMaps.config
Redirect this https://our.umbraco.org/Documentation/Reference/Templating/Mvc/modelsbuilder
to
https://our.umbraco.org/Documentation/Reference/Templating/Modelsbuilder/
> Redirect to Umbraco Modelsbuilder docs

- OurUmbraco.Site/config/MeetupUmbracoGroups.txt
Introducing the BUUG (belgian umbraco user group)
> add Belgian-Umbraco-User-Group meetup

- OurUmbraco.Site/config/Notification.config
Noticed some small typos when I received the account approval email.
> Fix typos in account approval notification email

- OurUmbraco/Our/Examine/ExamineHelper.cs
Add a small change to exclude the broken-link.md page from the search results.
Fix for : https://github.com/umbraco/UmbracoDocs/issues/598
> Exclude broken link page

- OurUmbraco.Site/OurUmbraco.Site.csproj
- OurUmbraco.Site/Views/Partials/Videos/Home.cshtml
I think this makes sense. Eg. to have a menu item that is selected by default.
The menu item doesn't listed the individual years as the logic currently doesn't support browsing those without a category - but should this be supported as well?
> Videos: Added "All videos" menu item

- OurUmbraco.Site/Views/Partials/Community/MVPs.cshtml
Some users have kept the @ in front of the username, so there are actually two @@ in front of their username. This commit will trim the username to make sure there is only a single @.
This appears to be isolated to the MVPs list as the profile page doesn't suffer from it.
> MVPs: Trim leading @ from social usernames

- OurUmbraco.Client/src/scss/pages/_documentation.scss
- OurUmbraco.Site/OurUmbraco.Site.csproj
- OurUmbraco.Site/packages.config
- OurUmbraco/Documentation/Busineslogic/MarkdownLogic.cs
- OurUmbraco/OurUmbraco.csproj
- OurUmbraco/packages.config
Switch documentation Markdown conversion to use Markdig so that it supports all things GitHub such as tables and GFM code blocks
> Switch documentation Markdown conversion to use Markdig 

- OurUmbraco.Site/config/YouTubePlaylists.json
This isn't a big change but I guess every little helps, right? ;-)
I noticed "UmbraCoffee" was spelt wrong (UmbraCofee) in the new YouTubePlaylists.json so I've fixed it...
> Correcting spelling of UmbraCoffee in YouTubePlaylists.json

- OurUmbraco.Site/Assets/js/lib/markerclusterer.js
- OurUmbraco.Site/Assets/js/map/community.map.js
- OurUmbraco.Site/Assets/js/map/profile.map.js
- OurUmbraco.Site/OurUmbraco.Site.csproj
- OurUmbraco.Site/Views/Partials/Community/Hub.cshtml
- OurUmbraco.Site/Views/Partials/Community/Map.cshtml
- OurUmbraco.Site/Views/Partials/Members/Profile.cshtml
- OurUmbraco/Community/Map/MapApiController.cs
- OurUmbraco/Community/Map/MapEventHandler.cs
- OurUmbraco/Community/Map/MemberLocation.cs
- OurUmbraco/Our/Controllers/ProfileController.cs
- OurUmbraco/Our/Models/ProfileModel.cs
- OurUmbraco/OurUmbraco.csproj
Adds a PR to bring back the old member location Google Map - users have to opt in by giving their lat & lon on their member profile. So it's totally optional.
* Adds Examine OnGatheringNodeData event - to add new field to index - used to help filter/find members who have lat/lon info on their profile
* Adds an API Controller - to query Examine for members who have Lat & Lon fields set
* Simple partial view that uses CDF to require the JS it needs
* External JS file for loading our markers from API endpoint & the marker info window
* Adds Google's community library for clustering markers
**Note**
We need to test how well this performs with more/real world data than in the test DB.
> Google Map - Display members around the world

- OurUmbraco/Community/Twitter/TwitterService.cs
Was expecting twitter to throw some kind of unauth ex, but we get a null. Now we return an empty array so the view doesn't blow up/throw a 500
Done as this was annoying me on local debug copy, when homepage fired up it would throw due to a null trying to be iterated on in the view
> Fixes twitter on homepage if keys are invalid

- OurUmbraco.Site/Views/Partials/Community/Map.cshtml
- OurUmbraco/Community/Map/MapApiController.cs
- OurUmbraco/Community/Map/MemberLocation.cs
Removes GitHub, Twitter & Karma count from the marker Pins & API response. We still sort members by karma though for many users at location when zoom level is close.
> Be less of a creep!

- OurUmbraco/Gitter/GitterUmbracoEventHandler.cs
Better error handling for trying to connect to rooms that do not exist
> Fix Gitter Bootup issue - if room no longer exists

- OurUmbraco/Community/Map/MapApiController.cs
Where some users are using local uploaded avatars and do not use Gravatar.
Checks for local avatar first before falling back to Gravatar
> Fixes #208 - Use Local Avatars if found for Community Map Markers

- OurUmbraco.Site/Assets/js/gitter/gitter.signalr.js
- OurUmbraco/Gitter/GitterApiController.cs
- OurUmbraco/OurUmbraco.csproj
Fixes Issue #200 
Adds API controller to look up gitter username (which we assume is same as github username)
JS monitors DOM & if new chat message added that contains span with data attribute we make an API call to check to see if we can find that user/member.
If so then we update the HTML with a link to that members profile
> #200 - Gitter Mentions

- OurUmbraco.Site/Views/Partials/SearchResults.cshtml
The icon to the left in each result result item isn't rendered properly since the statement outputting the class name hasn't been converted from the old WebForms.
With this commit, I've changed the line so it uses the proper Razor syntax, and the results then look like as shown below:
> WebForms? Yikes!

- OurUmbraco.Site/config/CommunityBlogs.json
Rewrote my blog and RSS feed so that it know supports filtering by tags 😃
> Blogs: Should only include Umbraco related posts

- OurUmbraco/UmbracoAuthorizationFilter.cs
`UserType` property is deprecated, but we can instead access `Groups ` property and check of any of these match "admin".
> Update deprecated UserType

- OurUmbraco.Site/Views/Master.cshtml
Super small update as I noticed the site footer still referenced our.umbraco.org rather than our.umbraco.com. Picked up the other domains in the master template while I was there.
> Updated master template and footer links to the new .com domain

- OurUmbraco.Site/Views/Partials/Forum/Thread.cshtml
- OurUmbraco.Site/Views/Partials/Forum/TopicForm.cshtml
- OurUmbraco.Site/scripts/forumsignalr.js
Hey folks,
I've done some work so that a logged in comment owner or admin can manage (read: edit or delete) a post upon creation.
This is from issue #260. Eventually we could extend this to have the topic owner involved to "Mark as Solution" but that feels outside of the scope of the PR.
Thanks,
Jamie
> Fixes Issue #260 edit new posts

- README.md
Fixed capitalization in headings and of GitHub and Umbraco words; added blank lines after headings, dots at the end of sentences and made `our.umbraco.org` clickable.
> fixed formatting, punctuation and capitalization in README

- OurUmbraco.Site/config/IISRewriteMaps.config
Make sure https://our.umbraco.com/documentation/getting-started/setup/install/permissions redirects to https://our.umbraco.com/Documentation/Getting-Started/Setup/Server-Setup/permissions where the article has been moved to.
> Added rewrite

- OurUmbraco.Site/config/IISRewriteMaps.config
Don't worry, I've just moved it to the Editor section, that already had something for it.
> Removed Fieldtype section in Forms Developer

- OurUmbraco.Site/web.template.config
When first getting the Our website to run locally the database reported timeout issues as it has a lot of upgrading/migrations to do.  The default connection timeout is 15 seconds.  I've set it to be 5 minutes in the template web.config.
> Increasing the db connection timeout in template web.config

- OurUmbraco.Client/src/scss/elements/_markdown-syntax.scss
Seems I didn't test the colors for XML syntax highlighting for my other PR, as the colors are better for light themes. So with this PR, I'm turning:
into:
The latter is based on the default theme from VS Code, which has a dark background similar to the Our forum.
> Improved colors for XML syntax highlighting

- OurUmbraco.Site/Views/Partials/Forum/TopicForm.cshtml
This minimise button looks so much like a download button that it's actually pretty misleading. I've changed the icon to a downward triangle so it's easier for a first time user to know what they can do here.
> Change to topic form icon from download to a down arrow

- OurUmbraco.Client/src/scss/elements/_member.scss
- OurUmbraco.Client/src/scss/elements/_roles.scss
I've found inconsistency between styling of badges for the member on Our. It had different styles and states on various places, so I've decided to fix it.
This is how it looks now (before fix, outiside of the thread): https://cl.ly/81c4f74b0943
In the thread: https://cl.ly/9b932c75f734
---
And after small fixes..
Profile: https://cl.ly/c496799f2003
Thread: (stays same)
---
I was trying to fetch the thread styling - dunno if it's the desired / consistent one to keep. We can always get back to colored version of it as well, but I was really annoyed by the underline kept there no matter of hovering over or not.
Feedback more than welcome!
> Consistent styling for member badges

- OurUmbraco/Our/Examine/ExamineHelper.cs
As this is hard to find out problems in the yaml as github does not shows this.
Just spend an hour on trying to find out what was happening with YAML not being interperted.  It was a space after the "---" marker.
> Remove the trailing spaces from yaml markers

- OurUmbraco.Site/Views/Partials/Members/PublicProfile.cshtml
- OurUmbraco.Site/web.template.config
Reported here: https://twitter.com/waltza86/status/1084047844464570368
The issue was caused by two bugs:
**IIS rewrite rule**
The rewrite rule would match usernames against `(\w+)`. `\w` is short for `a-zA-Z0-9_`, which doesn't include hyphens. The regex also didn't wrap to the end of the line, which was why it still matched `Matthew` even though the URL contained `Matthew-Wise`. Both should be fixed now.
**Search in Examine**
The search in Examine may reveal partial matches. So when searching for `github:Matthew`, Examine would return more than one result, and we would just pick the first and display the profile for that member.
With the PR, we're doing an extra check in C#/Razor to verify show the profile for the correct member.
> Fixed issue with GitHub usernames

- OurUmbraco.Site/Views/Partials/Releases/ReleasesDropdown.cshtml
- OurUmbraco/Our/Models/Releases.cs
- OurUmbraco/Our/Services/ReleasesService.cs
The release compare page now links to either the YouTrack issue or the GitHub issue based on it's source.
Issue: #345
> Fixing the Release Compare Issue tracker URL's.

- OurUmbraco.Client/src/scss/elements/_packages.scss
- OurUmbraco.Site/Views/Partials/Projects/ListProjects.cshtml
This is a fix for issue #320 
Rather than cropping as the ticket suggested, I have just set the max height and width to be 64px square as this was already the max width. The problem with setting a crop is the package owner would have no control over how their image is cropped. This way, we can inform package owners of the exact dimensions and it's up to them to upload an image that works.
> Small fix for the icons shown in the package search results.

- OurUmbraco.Client/src/scss/elements/_markdown-syntax.scss
- OurUmbraco.Site/OurUmbraco.Site.csproj
- OurUmbraco.Site/packages.config
- OurUmbraco/Documentation/Busineslogic/MarkdownLogic.cs
- OurUmbraco/OurUmbraco.csproj
- OurUmbraco/packages.config
As the JSON examples used throughout the documentation doesn't follow the JSON specification 100%, I realized I had to adjust my syntax highlighter package a bit (see some discussion [here](https://github.com/umbraco/UmbracoDocs/pull/1250)).
Where the old version of my package used the old ColorCode from Microsoft (which had some bugs on it's own), I decided to write my own JSON tokenizer/parser, which then gives a number of benefits - eg. comments and strings that are not properly enclosed with double quotes.
As GitHub doesn't like invalid JSON either, @jmayntzhusen suggested we could use `json5` (human friendly JSON, that is) instead of `json`, I've also updated my Markdig extension and the code for Our to allow setting `json5` as an alias of JSON.
> Updated the syntax highlighter

- OurUmbraco.Site/Views/Partials/Members/Register.cshtml
Noticed a typo when signing up. So thought I would fix it!
> Fix typo in GitHub label description

- OurUmbraco.Client/src/scss/sections/_docs.scss
- OurUmbraco.Site/Views/DocumentationSubpage.cshtml
- OurUmbraco.Site/Views/Partials/Documentation/DisplayMarkdown.cshtml
- OurUmbraco.Site/config/ExamineIndex.config
- OurUmbraco/Our/Examine/ExamineHelper.YamlMetaData.cs
- OurUmbraco/Our/Examine/ExamineHelper.cs
- OurUmbraco/Our/Examine/OurSearcher.cs
- OurUmbraco/Repository/Models/DocumentationVersion.cs
- OurUmbraco/Repository/Services/DocumentationVersionService.cs
Because all files have now a versionFrom (when https://github.com/umbraco/UmbracoDocs/pull/1574 is merged) we can turn the logic around to make sure that the file can be found a cross multiple versions.
To test: 
Search for Tours (v7) will return content.  Currently "Tours" with v8 won't return content.
If this PR (and the docs PR) is merged, the v8 will return the same content as v7 as there is no difference in the documentation for the "tours" section.  If you search for v6, there should be no results.
> cross search version 7 and 8 on umbraco docs

- OurUmbraco/Community/BlogPosts/BlogPostsService.cs
As reported in #406, the date parsing in RSS feeds didn't quite work as expected.
My `TimeUtils.Rfc822ToDateTimeOffset` method used for the parsing actually does what it should, but the returned value was never used as it was immediately overwritten by `DateTimeOffset.TryParse`.
> Fixed RSS date parsing

- OurUmbraco.Site/Views/Partials/Navigation/TopNavigation.cshtml
The contribute navigation button didn't work as it has the branch name in the link, and the branches were recently restructured with different names.
Claus has fixed it directly on the live site, but this will need to be merged in for the next deployment so we don't overwrite his change with the error again 🙂
> Fix broken link after renaming branches in the CMS

- OurUmbraco.Site/config/uVersion.config
Umbraco 7.14 was released a couple of weeks ago but currently doesn't show up on the list of available versions for packages... I have updated it here!
> Add v7.14 option to version.config

- OurUmbraco.Site/Views/Partials/Documentation/DisplayMarkdown.cshtml
- OurUmbraco.Site/config/ExamineIndex.config
- OurUmbraco/Our/Examine/ExamineHelper.YamlMetaData.cs
- OurUmbraco/Our/Examine/ExamineHelper.cs
- OurUmbraco/Repository/Models/DocumentationVersion.cs
- OurUmbraco/Repository/Services/DocumentationVersionService.cs
It is currently not possible for the Docs Curators to remove the note at the top warning people that the article hasn't been tested for v8. We had a discussion at our last meeting and would like to set a YAML tag on all the sections where it makes sense, then those can show the note - it would work as a sort of reminder of what is still in need of an update / check.
Have added functionality where a YAML tag can be set and then it will only show the note if that is not set. To enable the note we would simply set `needsV8Update: "true"`. We will shortly be rolling out a Docs PR that will add this tag to all articles that currently has the note 🙂 Which is why this is currently a draft PR.
> Make removing the v8 warning note possible

- OurUmbraco.Client/src/js/app.js
As reported by in #439, the mobile navigation is broken on the live site. I can't however reproduce this locally with the newest code, but inspecting the code on the live site, it appears to be the same.
I played a bit around in the console of the browser on the live site, and placing the click event on the `a` instead of the `div` seems to fix this. But I can tell for sure as I can't reproduce it locally.
> Fixed mobile navigation issues on the front page (maybe)

- OurUmbraco/Community/Twitter/TwitterService.cs
Twitter has made some breaking changes, meaning that some JSON properties in the user object that used to be returned by their API are no longer there. This breaks Tweetinvi, and apparently the developer wont be able to release an update to address this for some months.
Our's current implementation of the Twitter feed makes a request to get information about the authenticated Twitter user. As Tweetinvi are no longer able to parse the response, the feed fails.
The solution is therefore just to remove the line, as apparently isn't used for anything. I tried to remove the line in my local setup, and the feed now works again.
> Twitter: Removed call to get authenticated user

- OurUmbraco.Site/Views/Partials/Documentation/Breadcrumb.cshtml
Currently the index filename is included in the breadcrumbs for versioned files, this PR will remove that.
Current state:
After this fix:
> Remove breamdcrumb for versioned files

- OurUmbraco.Client/src/scss/sections/_docs.scss
As part of the new Umbraco identity on Our the green note was changed to blue. We already have a blue tip though, I think in this instance it should stay the old color to differentiate 🙂
> Revert color change to the note for documentation

- OurUmbraco.Site/Views/Partials/Projects/ListProjects.cshtml
- fixed the issue with the headline showing as most popular packages by default when we are actually seeing latest packages.
So now it depending on the order mode it will show as 'latest', 'recently updated' or 'most popular'.
This fixes issue #449
> - fixed the issue with the headline showing as most popular packages

- OurUmbraco/Community/GitHub/GitHubService.cs
- OurUmbraco/Our/Services/ContributorBadgeService.cs
If at first you don't succeed, try again 😄 
With PR, the service will look up a member a GitHub user ID with a very specific raw SQL query instead of using the member service, which has quite a bit of overhead.
The raw query will find the ID of the member, and the member service is then still used to get an instance of `IMember` representing that member.
> ContributorBadgeService: improved the way we find members by their GitHub user IDs

- OurUmbraco.Site/Views/Partials/Projects/ProjectDetails.cshtml
The analytics.js script was no longer loaded on Our after a switch was made from analytics.js to Google Tag Manager. For the UA code of Package owners to properly trigger, the above code is needed.
> Updated Google Analytics script to load library

- OurUmbraco.Site/Views/Partials/Home/Meetups.cshtml
- OurUmbraco.Site/Views/Partials/Home/TwitterSearchUmbraco.cshtml
This PR fixes issue [464](https://github.com/umbraco/OurUmbraco/issues/464).
On the home page of the site the meetup links and twitter activity links open in the same window. This PR addresses this issue.
Regards,
Poornima
> Home page - Open meetups and Twitter Activity in a new window

- OurUmbraco.Site/Views/Partials/Community/Home.cshtml
Hello,
I realised on PR #482 I had updated the logic but not the list on homepage of which repos are included for contributions, so I have added them now :)
Should look like this:
Thanks,
Carole
> updating repos list on page

- OurUmbraco.Site/Views/Download.cshtml
- OurUmbraco.Site/Views/Partials/Releases/AllReleases.cshtml
- OurUmbraco.Site/Views/Release.cshtml
- OurUmbraco.Site/Views/ReleaseLanding.cshtml
- OurUmbraco.Site/Views/ReleaseProgress.cshtml
- OurUmbraco/Our/Extensions/UrlExtensions.cs
I went down a bit of a rabbit hole, sorry...
It was really bugging me that the URL for each version on the ["all releases" page](https://our.umbraco.com/download/releases/) contained a double slash...
And then I noticed that some URLs elsewhere on Our point to the old `/contribute/releases/{version}` URL instead, so I decided a centeralised helper would be a nice way to fix this
> Cleanup release URLs

- OurUmbraco.Client/src/scss/elements/_search-big.scss
This pr changes the width of the docs search box to fill the entire horizontal space.
Before the change there was an empty gap after the version dropdown:
After the change:
Tested on (latest stable version of each browser):
Chrome 77
Firefox 69
Safari 13
IE 11
> Fix search box width

- OurUmbraco/Documentation/DocumentationContentFinder.cs
The code that sets "topicTitle" uses Request.RawUrl as a base for splitting the current page "path", reversing it and displaying it in <title />. Not sure if that's the best approach all round, but RawUrl includes the querystring which I'm sure sucks.
I've given up trying to run the website locally (everything and HTTPS seems to screw me over for more than an hour now) so this is **_untested_** (!!!), but I'm hoping someone (hi @nul800sebastiaan ;-) ) with a working local setup might be able to do a quick test to see if this oneliner fixes https://github.com/umbraco/OurUmbraco/issues/461 ? Pretty please?
> Potential fix for issue #461: Update DocumentationContentFinder.cs

- OurUmbraco.Site/Views/Partials/Projects/CompatibilityReport.cshtml
- OurUmbraco/Our/Utils.cs
- OurUmbraco/Project/Controllers/ProjectCompatibilityReportController.cs
We've had a talk at the London hackathon - it doesn't make sense to require downloading the package before you can report compatibility as it means noone really does it.
Seems the method was only ever used here, so cleaned up the model as well.
https://github.com/umbraco/Umbraco.Packages/issues/20
> Remove download requirement from voting on compatibility

- OurUmbraco.Site/config/uVersion.config
Seems the list of version to report compatibility on for packages is based on this list. Added 8.3 which was released today.
> Allow package voting for 8.3

- OurUmbraco/Documentation/DocumentationUpdater.cs
This adds Heartcore to the menu-order-building-whatever thingy so Heartcore stands next to Cloud.
Before:
After:
> Add link to Heartcore docs before contribute

- OurUmbraco/Our/Controllers/LoginController.cs
Fixes ArgumentNullException when no name is provided on Github
> Use Github username as fallback if no name is provided

- OurUmbraco.Site/Views/Partials/Projects/MyProjects.cshtml
- OurUmbraco/Our/Controllers/ProjectsController.cs
This proved very easy.. Not sure why this was never allowed.
This PR will make it so if you don't check the "make live" button at the end of creating a new package you will still be able to find it on your profile. 
I added a little status message on the package overview of the profile page, here is how it will look:
Closes https://github.com/umbraco/Umbraco.Packages/issues/28
> Allow seeing draft packages on profile page

- OurUmbraco.Client/src/scss/elements/_note.scss
- OurUmbraco.Site/Views/Partials/Navigation/TopNavigation.cshtml
- OurUmbraco.Site/Views/Partials/Projects/ListProjects.cshtml
Had some requests to not automatically redirect to the about packages page from the top menu.
Now it will redirect to the package overview as it used to, but have a banner at the top that links to the about page:
The style of the banner is the same as on https://our.umbraco.com/community/ and I have added a bit to the styling for it, but nothing that will affect the current banner as it doesn't contain <div> or <a> elements 🙂
> Package page banner

- README.md
I've updated the location to a recently generated database that can be used for running Our locally. 
I've also added a note about the user/password that can be used if your SQL Server instance has containment enabled.  
To enable containment you would need to run the following SQL.   
```
sp_configure 'contained database authentication', 1;  
GO  
RECONFIGURE;  
GO  
```
Using these credentials in your web.config connection string is super useful as it means that you won't need to reconfigure a login after each future DB restore.  But perhaps it's all sounding a bit complicated, so I should remove the sentence with the containment credentials?!
Am going to ask the rest of the Package Team to have a look at this and will submit the PR when some others have confirmed that this db works as …
> New anon db available to download

- OurUmbraco.Site/config/IISRewriteMaps.config
Since it's almost a year ago Umbraco 8 was relaesed, I'm removing the Docs status page.
PR: https://github.com/umbraco/UmbracoDocs/pull/2231
> Redirecting Umbraco 8 Docs status page to Docs pag

- OurUmbraco.Site/Views/Apps.cshtml
- OurUmbraco/Our/Services/PackagesService.cs
@nul800sebastiaan 
This implementation is not caching the db calls - it does 3 calls per page hit and the page is only for hq. Should it be cached?
I also left in the old GetPackageStatisticsData() method, but am not using it - should it just be removed? 🙂
> Package stats

- OurUmbraco/Documentation/DocumentationUpdater.cs
May have gotten ahead of myself and adding more levels of navigation than the website can render.
Let me know if this is the case :smile: I'm just happy that I found where this navigation was kept haha.
This alteration is based on a fuller contribution to UmbracoDocs (https://github.com/umbraco/UmbracoDocs/pull/2024).
As I've referenced all the links within the 3rd level navigation we could remove case 4 section if it isn't a quick fix to render - just let me know.
> Adding the Editor's Manual to Documentation Site

- OurUmbraco.Site/web.vsts.config
- OurUmbraco/Our/Api/InstallationController.cs
- OurUmbraco/Our/Api/UpgradeCheckController.cs
- OurUmbraco/Our/Models/InstallationModel.cs
- OurUmbraco/Our/Models/UpgradeModel.cs
- OurUmbraco/Our/Models/UpgradeResult.cs
- OurUmbraco/Our/Models/UpgradeResultModel.cs
- OurUmbraco/OurUmbraco.csproj
The purpose of this PR is to replace http://update.umbraco.org/checkforupgrade.asmx
Two endpoints have been created:
- **Install**
- This endpoint basically just writes to a database such that we have a count of installs of Umbraco
- **CheckUpgrade**
- This endpoint receives the current Umbraco version, and if there exists a newer version of that major, it returns the information about the latest version of this major - otherwise, a None result is returned.
Before starting:
- Make sure to follow the instructions on Our https://github.com/umbraco/OurUmbraco for how to set up the project locally. 
- After that execute the script uploaded as an attachment to the AB issue (AB4954)
- After restoring the DB and having configured a user, in your web.config in `<connectionStrings>` section, add: …
> Implementing REST endpoints to replace WCF

- OurUmbraco.Site/OurUmbraco.Site.csproj
- OurUmbraco.Site/robots.txt
Included the robots.txt file in the site project so it get's deployed to the website. At the moment there is no robots.txt file.
The robots.txt file is updated so it allows indexing the site, but prevents crawlers from following links to filedownload page.
This could be the cause of  why some very old packages still get daily downloads and show up in the popular packages search.
Jesper checked Google Analytics and confirmed that these are not triggered by clicking in the browser on the download button.
> Robots txt update

- OurUmbraco.Site/config/CommunityBlogs.json
See #568. I added my feed last year, but turns out it's an ATOM feed, which is not supported. 
Now converted to RSS using FeedBurner.
> Converted ATOM feed to RSS feed

- OurUmbraco.Site/Views/Partials/Projects/ListProjects.cshtml
- OurUmbraco.Site/Views/Partials/Projects/SortOrderDropdown.cshtml
- OurUmbraco.Site/Views/Projects.cshtml
- OurUmbraco/Repository/Controllers/PackageSortOrder.cs
- OurUmbraco/Repository/Models/Package.cs
- OurUmbraco/Repository/Models/PagedPackages.cs
- OurUmbraco/Repository/Services/PackageRepositoryService.cs
For #554 
this has extended the `PackageRepositoryService` a little, but we have not changed any of the existing information used by the back office. 
**Because the Service returns everything with the base URL when you are testing this, all the package results will have fully qualified URLs to our.umbraco.org. (not your local site).**
I am not sure how to check the back office elements are still working, can i change something in a standard umbraco install to point its package list to my own version of our ?
> Unify Package search #554

- OurUmbraco.Client/src/scss/elements/_profile.scss
- OurUmbraco.Site/Views/Partials/Projects/MyProjects.cshtml
A quick refresh of the edit / forum / team buttons on the package list to better go with the rest of the site.
Desktop:
Mobile:
> Improved the look of the buttons on the package list

- OurUmbraco.Client/src/scss/sections/_packages.scss
closes https://github.com/umbraco/Umbraco.Packages/issues/52
As the categories aren't that useful I've decided to just hide them on mobile rather than to take up the already limited space with them.
> hide category list when in mobile size

- OurUmbraco.Site/App_Plugins/OurManagement/ourmanagement.controller.js
- OurUmbraco.Site/App_Plugins/OurManagement/ourmanagement.html
- OurUmbraco/Our/Api/DocsController.cs
- OurUmbraco/Our/Examine/ExamineHelper.cs
- OurUmbraco/OurUmbraco.csproj
If we don't catch errors and there is a syntax error in the meta tags, indexing will stop and search will not be working again (for documentation) on our.
> catch exceptions while indexing yaml meta tags

- OurUmbraco.Site/Views/Partials/Community/Home.cshtml
- OurUmbraco.Site/config/GitHubPublicRepositories.json
- OurUmbraco/Community/GitHub/GitHubService.cs
I believe this is what is required to get the PRs to the UmbPack repo included in the contributions list on the Our home page.  Seeing the repository name in the list may encourage people to have a look to see if they can contribute!
> adding umbPack as an umbraco public repo

- OurUmbraco.Client/src/scss/elements/_markdown-syntax.scss
As part of https://github.com/umbraco/UmbracoDocs/issues/2045, I suggested a new blue box for links, which given the blue color would be easier to see than a regular list of links. Sorta like the *call to action* links we typically make for our client's websites.
Per @jmayntzhusen's suggestion, you can then write something like:
```
:::links
- [`<umbLoadIndicator />` in the **API documentation**](/apidocs/v8/ui/#/api/umbraco.directives.directive:umbLoadIndicator)
- [`<umbLoadIndicator />` source code on **GitHub**](https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web.UI.Client/src/common/directives/components/umbloadindicator.directive.js)
:::
```
Technically you can add anything as the content of the box, but I've only added styling for an unordered list - and an …
> Added styling for new links box

- OurUmbraco/Project/Api/ProjectUploadController.cs
This is conjunction with https://github.com/umbraco/UmbPack/pull/27 will ensure that a new package pushed via UmbPack will update the current version to whatever the package file has set in its package.xml:
> Grabs pkg version from form and updates the content node accordingly

- OurUmbraco/Our/Examine/ProjectNodeIndexDataService.cs
- OurUmbraco/Wiki/BusinessLogic/WikiFile.cs
Using the new dev db, rebuilding 'projectIndexer' returned 0 documents for me because of two errors.
As there is no data in the ```projectDownload``` table, the most recent download date returned is ```DateTime.MinValue```.  The code then falls over when trying to subtract 365 days from the returned date (of course can't have a date earlier than MinValue). This will only be an issue when using the new db. This PR changes it to not query the db and just return empty collection in this instance.
The other error was that the database was returning NULL for the ```removedBy``` column for the one record in the ```wikiFiles``` table, and the ```RemovedBy``` property of the ```WikiFile``` class is a *non-nullable* int.  I've implemented a workaround so am now able to get the index rebuilt and …
> fixes required to rebuild 'projectIndexer' with new dev db

- OurUmbraco/Our/Examine/ProjectPopularityPoints.cs
Comment in code says `// add the nuget downloads for the last 6 months` but actually it was only doing it for the last 6 days. 
updated to work it out for last 6 months. *(also want to confirm my re naming of branches works)*
> Calculates the nuget downloads for 6 months (not days) as per comment

- OurUmbraco/MarketPlace/NodeListing/NodeListingProvider.cs
This will fix https://github.com/umbraco/Umbraco.Packages/issues/44
Update 21st of April 2020:
The reason this hasn't been merged yet is that you will be able to create a package with the same name as an existing package as long as it is under a different category.
Fx. Call a package Umbraco Forms that is under Starter kits..
This is currently possible as well if you create a new package, so before this gets merged in some consideration is needed on how we can fix that issue.
Additionally if you rename it to an already existing name it will call it "Existing Name(1)" just like when making a node in the backoffice.
> Allow renaming packages

- OurUmbraco.Client/src/scss/elements/_sidebar.scss
- OurUmbraco.Client/src/scss/pages/_documentation.scss
This makes it way easier to spot where you are by making the active link bold in the sidebar. Example shown below.
**Current**:
**Now**:
> Highlight active documentation page

- OurUmbraco.Site/App_Plugins/OurManagement/ourmanagement.controller.js
- OurUmbraco.Site/App_Plugins/OurManagement/ourmanagement.html
- OurUmbraco/Our/Api/MembersController.cs
This PR will make it possible for me to add enough karma to new users to be able to upload packages.
It uses the existing backoffice dashboard, here is an example 🙂
Main question I have is whether we should set both the total and current rep points? Not sure what the difference between them is, all I know is the total rep points need to be above 30 for the package upload part.
> Grant member karma

- .github/ISSUE_TEMPLATE/1_Bug.md
- .github/ISSUE_TEMPLATE/2_Feature_request.md
- .github/ISSUE_TEMPLATE/config.yml
Having issues templates will, hopefully, encourage people to report package related issues over on the Package Team repository, not here.
I don't think I can test how these are going to look without you merging this!
Kept the templates simple as you suggested @nul800sebastiaan 
Thought I better do this today so you didn't mistake this for my Umbraco Hacktoberfest contribution 😉
> add templates for bug and feature request, plus a link to the packages repo

- OurUmbraco.Site/Views/Download.cshtml
We already do this on the individual release-pages. Now we should get more real data. 
This is done blindly, as I'm on my mac today - so please test :-p @nul800sebastiaan
> Track downloads from main download-page

- OurUmbraco.Site/Views/Partials/Project/Edit.cshtml
- OurUmbraco/Our/Models/ProjectDetails.cs
Added regex model validation to check if the entered string contains nuget.org
Fixes: #611
> 611 Cannot publish package if I don't enter the full NuGet URL

- OurUmbraco.Site/Views/MacroPartials/Projects/MyProjects.cshtml
- OurUmbraco/Our/usercontrols/ProjectEditor.ascx
- OurUmbraco/Project/usercontrols/Deli/Profile/__MyProjects.ascx
The "get in touch with us" pointed to : https://umbraco.com/about-us/team/ which does not exist.
I thought it be better if it led the user to the contact us page: https://umbraco.com/contact-us/
(thats at least where I asked to get that restriction lifted 😀)
I updated all links to that particular page in the code.
> Update link in Our>Profile>Packages

- OurUmbraco.Site/Views/Partials/Projects/ListProjects.cshtml
stops the next button appearing at the end of the search pagination when you reach the last page.
> fixes #66 - Next button shows on last page of search

- OurUmbraco.Client/src/js/app.js
- OurUmbraco.Client/src/scss/elements/_profile.scss
- OurUmbraco.Site/Views/Partials/Projects/MyProjects.cshtml
- OurUmbraco/Our/Controllers/ProjectsController.cs
- OurUmbraco/Our/Models/MyProjectsModel.cs
This relates to https://github.com/umbraco/Umbraco.Packages/issues/56
Previously all packages were listed in alphabetical order with no indication of their 'status', i.e. whether they were Active, Draft or Retired
This PR now groups members' packages by status, with Active, then Draft, then their Contributions (already a separate listing), followed by 'Retired'. Hopefully this will encourage package developers to retire active packages more often.
For example:
If they have no packages then no headings appear, just the 'add' button:
> Reorganising member package listing to be under 'status' headings

- OurUmbraco.Site/config/IISRewriteMaps.config
Turns out that link from google directs to Set-up/Umbraco-Latch, which is the wrong path.
> Re-add rewrite for Latch article

- OurUmbraco.Client/src/scss/sections/_packages.scss
- OurUmbraco.Site/Views/Partials/Projects/ListProjects.cshtml
- OurUmbraco.Site/Views/Partials/Projects/ProjectDetails.cshtml
Fixes potential layout issue when packages reach 1 million downloads
see : https://github.com/umbraco/Umbraco.Packages/issues/107
this update changes the number format for downloads to display in 1000's (e.g 134.5K) or millions (1.1M) on both the package listing and package info pages. 
should also resolve the alignment issue on the package listing page, where the bottom of the boxes doesn't always line up:
For layout, 
becomes (the version and download info is now aligned).
> Fix package listings layout and downloads counts

- OurUmbraco.Site/Views/Partials/Projects/MyProjects.cshtml
This PR fixes a regression introduced by https://github.com/umbraco/OurUmbraco/pull/563
The button to manage API Keys to use with the UmbPack tool are now shown for owners of packages again:
> Enable Api keys button on package overview page

- OurUmbraco.Site/config/TeamUmbraco.json
Does what it says on the tin... I have added the [new community team members](https://umbraco.com/blog/the-community-teams-applications-20202021/) to the teams JSON file.
The file is used to identify team member activity and track stats.
> Adding the new team members to the stats

- OurUmbraco.Site/Views/Partials/Community/Home.cshtml
- OurUmbraco.Site/config/GitHubPublicRepositories.json
- OurUmbraco/Community/GitHub/GitHubService.cs
The [Package.Templates repository](https://github.com/umbraco/Package.Templates) now has contribution guidelines, so could it be listed to the list of repos that are considered for home page stats?  If so this PR adds this to the home page links, the json and the GitHub service (i.e. all the places that were updated in this commit: https://github.com/umbraco/OurUmbraco/commit/d9603fd85a274cd332b36daa9bbf2cb35d1e8ec7 when adding umbPack)
Don't know what the order of things should be, but I've added it after UmbPack:
> adding Package.Templates as an umbraco public repository

- OurUmbraco/Community/Nuget/NugetPackageDownloadService.cs
Also logging the nuget package id in case this  occurs
> Fix for null reference in nuget download service

- OurUmbraco.Site/web.vsts.config
**This PR is dependant on a Docs PR: https://github.com/umbraco/UmbracoDocs/pull/3092.
Do not merge this before the Docs PR has been merged.**
We're in the process of implementing a new Getting Started section in the Documentation.
The current "Getting Started" section will be renamed Fundamentals.
The rewrites added in this PR should make sure that everything from the old Getting Started section is redirected over to the Fundamentals section.
There is a rewrite rule for each if the sub-sections in the Getting Started section, and they are redirected to their new path in the Fundamentals section.
> Rewrites for the new Fundamentals section of docs

- OurUmbraco.Site/web.vsts.config
I've tested this on my local instance of Our, and links to the "old" Getting Started section, should now redirect correctly to the same article within the new Fundamentals sections.
E.g.
`/documentation/getting-started/backoffice/property-editors/built-in-property-editors/Nested-Content/`
now redirects to
`/Documentation/Fundamentals/Backoffice/property-editors/built-in-property-editors/Nested-Content/`
instead of "just" the `/Documentation/Fundamentals/Backoffice/` index page.
> Update rewrite rules for new Fundementals section.

- OurUmbraco/Repository/Models/Package.cs
- OurUmbraco/Repository/Services/PackageRepositoryService.cs
This change is to support a change to the Packages section in the Umbraco office, allowing the display of a badge or similar for those packages that are certified to work with Umbraco Cloud.
> Added flag for packages certified to work on Umbraco Cloud to the packages API response.

- OurUmbraco.Site/Views/Partials/Documentation/DisplayMarkdown.cshtml
We want to have the versions box show, whenever the "versionFrom" meta data is used on an article.
> Always show versioning box

- OurUmbraco.Site/App_Code/RenderProjectHelpers.cshtml
- OurUmbraco.Site/OurUmbraco.Site.csproj
- OurUmbraco.Site/Views/Partials/Projects/ListProjects.cshtml
- OurUmbraco.Site/Views/Partials/Projects/ListPromotedProjects.cshtml
- OurUmbraco.Site/Views/Projects.cshtml
- OurUmbraco.Site/config/ExamineIndex.config
- OurUmbraco/Our/Examine/ProjectNodeIndexDataService.cs
- OurUmbraco/Our/MigrationsHandler.cs
- OurUmbraco/Our/Utils.cs
- OurUmbraco/Repository/Controllers/PackageRepositoryController.cs
- OurUmbraco/Repository/Models/Package.cs
- OurUmbraco/Repository/Services/PackageRepositoryService.cs
This PR adds the option for flagging certain packages as "promoted" (planned for HQ, as a technical partner benefit and to support selected community packages).  By selecting a package as promoted it'll appear in a new section under "Popular" and above "Latest", and also expose the information via the API so we can do a similar thing in the back-office.
Requires a new property on the "Project" document type:
```
Tab: Project
Alias: isPromoted
Name: Is Promoted?
Description: The package is selected for promotion (HQ, technical partner or selected community package).
```
I've reworked the templates slightly to allow for hiding of the whole "Promoted" section if there are none to promote, which required a new partial, and then to share some common helpers and functions between the new and …
> Adds back-office management, display and API updates to support promoted packages in the back-office and on our.umbraco.com.

- OurUmbraco.Site/web.vsts.config
- OurUmbraco/Documentation/DocumentationUpdater.cs
In order to not have a folder called "V9-Config" in the documentation, I've had to move the articles around and add a couple of new folders.
This will require a set of rewrite rules, which I've added here.
The rules have been tested on a local instance of Our.
**This shouldn't be merged until the related PR (https://github.com/umbraco/UmbracoDocs/pull/4020) has been merged on the Docs**
> Adding rewrites for moved folders

- OurUmbraco/Documentation/Busineslogic/MarkdownLogic.cs
The documentation curators where thinking to enable the nofollow on the documentation to discourage people putting external links.
> Enable NoFollow links on documentation

- OurUmbraco.Site/config/IISRewriteMaps.config
First link adds a rewrite after a change to a path.
Second link adds a rewrite to a strange path generated/indexed by Google - this fixes https://github.com/umbraco/UmbracoDocs/issues/4232
> Couple of rewrites for the Docs

- OurUmbraco.Site/Views/Partials/SeoCanonical.cshtml
Canonicals for UmbracoCMS documentation were pointing to the main docs page. Getting started documentation canonicals were pointing to the wrong url on docs.umbraco.com
> Fix for canonicals in documentation

- OurUmbraco.Site/config/CommunityBlogs.json
Adding our blog at MCB where we once in a while blog about Umbraco related topics.
https://blog.mcb.dk/en/tag/umbraco
Not sure if the id is just a random generated guid?
I noticed the id referring the blog from @glombek is without hyphen and the logo/avatar is the following:
https://2.gravatar.com/avatar/6e03aef14c3e69d4e14b111b10d480a70ecc5a60a7dd5975472a68c06f5b48e8?size=256
but the same version here - maybe preferable.
https://gravatar.com/avatar/6e03aef14c3e69d4e14b111b10d480a70ecc5a60a7dd5975472a68c06f5b48e8?size=256
> Add MCB blog

- OurUmbraco.Site/config/CommunityBlogs.json
I noticed a broken logo/avatar here:
https://community.umbraco.com/learn-about-the-community/blog-posts/?page=5
which point on https://our.umbraco.com/media/blogs/574d8335-d429-4ff7-8877-dcd863206eae.png
According to the JSON file it should use this logo though, which doesn't exist either.
https://michaels-ugarage.cyber-solutions.at/media/v4lbwrd2/logo.png
I updated to https://michaels-ugarage.cyber-solutions.at/media/v4lbwrd2/logo.png
Maybe @ReiterM2000 can confirm it should use this as logo instead?
> Fix broken logo

- OurUmbraco.Site/Views/Master.cshtml
Maybe I am being overly critical, but I think it's a good idea to remove the version number from the footer, especially since Umbraco 7 is end of life.
> Remove version number from footer

- OurUmbraco/Our/Api/UpgradeCheckController.cs
There was a [query raised on the CMS tracker](https://github.com/umbraco/Umbraco-CMS/issues/17910) around what the 4th part of the version number reported on an upgrade check meant.
Give we only release for upgrades versions with major.minor.patch - the fourth revision part is always 0 and hence superfluous, so we could remove it to avoid confusion.
I've done this in this PR for V7 and above (seems like back in time we did use the revision part, but we haven't for many years).
Confession time... I tried and failed to get our.umbraco.com running locally 🙈, so I haven't tested this in situ (only in some throwaway code).  So it does need checking before deploying even if it looks correct.
> Limit version number reported in upgrade check to 3 parts
