OurUmbraco.Site/Views/MacroPartials/Projects/ProjectDetails.cshtml
Amended the project's tags to be comma-separated.
=> OUR-150 Project page - tags not comma-separated

OurUmbraco.Site/Views/MacroPartials/Projects/ProjectDetails.cshtml
Wraps the .NET version number with a conditional check.
=> OUR-149 .NET version - displays if empty

OurUmbraco.Site/masterpages/Master.master
Related to this issue: http://issues.umbraco.org/issue/OUR-198
=> Removed meta-tag robots: noindex

OurUmbraco.Site/Views/MacroPartials/Forum/ForumActions.cshtml, OurUmbraco.Site/Views/MacroPartials/Forum/TopicForm.cshtml
Just a couple of quick fixes for the mentioned issues.
=> Typos OUR 272 and OUR 273

OurUmbraco.Site/Views/MacroPartials/Projects/ProjectDetails.cshtml
Added a edit link for project owner and contributers to easy go to the
project edit page.
=> Add edit link for project owner and contributers

OurUmbraco.Client/src/scss/elements/_package-detail.scss, OurUmbraco.Site/Views/Partials/Projects/CompatibilityReport.cshtml
Fix for a display bug in Safari.
=> Fix for OUR-257 (Report Compatibility display bug in Safari)

OurUmbraco.Site/masterpages/Master.master
Fixing step 1 and 2 of this issue: http://issues.umbraco.org/issue/OUR-85
=> Upgrade to Universal Analytics (Google Analytics)

OurUmbraco.Client/src/scss/elements/_member.scss
Added the styling for the solved posts on the public member page. So solved posts get the green background as it has all other places
=> OUR-299: Make consistency on showing solved posts on public member page

Notification/NotificationTypes/MarkAsSolutionReminder.cs, Notification/NotificationTypes/MarkAsSolutionReminderSingle.cs, Notification/NotificationTypes/NewForumTopic.cs, Notification/NotificationTypes/NewForumTopicComment.cs
Fix for OUR-327 - only by replacing the actual strings in the code.
=> Change from HTTP to HTTPS in notification links

OurUmbraco.Site/Views/MacroPartials/Projects/ProjectDetails.cshtml
Fixing this issue: http://issues.umbraco.org/issue/OUR-326
=> Add some Analytics-info for packagemakers

OurUmbraco.Site/Views/Partials/Members/Profile.cshtml, OurUmbraco.Site/Views/Partials/Members/Register.cshtml
Update avatars for retina screens.
http://issues.umbraco.org/issue/OUR-309
=> Update avatars with srcset for retina screens

OurUmbraco.Client/README.md
Just a couple of tweaks from *The Central Scrutinizer* :)
=> A few fixes for the README

OurUmbraco/Project/usercontrols/Deli/Package/Steps/Files.ascx.cs
Added the most recent ASP.NET versions for the dropdown list
=> Package upload: Updated ASP.NET version numbers

OurUmbraco/MarketPlace/Providers/KarmaProvider.cs, OurUmbraco/Our/Utils.cs, OurUmbraco/OurUmbraco.csproj, OurUmbraco/Repository/Controllers/PackageRepositoryController.cs, OurUmbraco/Repository/Models/Package.cs, OurUmbraco/Repository/Models/PackageDetails.cs, OurUmbraco/Repository/PackageRepositoryService.cs, OurUmbraco/Repository/RepoStartupHandler.cs, OurUmbraco/Repository/Services/PackageRepositoryService.cs, OurUmbraco/Wiki/BusinessLogic/WikiFile.cs
This task is part of U4-8156, at CGRT16
=> Package Repo REST API

README.md
this is refering to unexisting usercontrol
=> OUR-436 update documentation section

OurUmbraco/Documentation/DocumentationContentFinder.cs
see http://issues.umbraco.org/issue/OUR-437
What this pull request changes is the way the github url is build.
With this pull request we are looking up the file on disk, then rebuild the filename (including correct casing) from the complete filepath.  This appears the only reason to get this working.
NTFS is case sensitive but the windows API's are not.  Therefor there does not seem to be another way to retrieve a properly cased file path.
=> OUR-437 fix casing of md file in case incoming URL has incorrect casing

OurUmbraco.Site/Views/Partials/Community/Home.cshtml, OurUmbraco.Site/Views/Partials/Home/GitHubContributors.cshtml
Changed link to contribute link and wording to commits
=> Github contributors

OurUmbraco/Community/Controllers/GitHubContributorController.cs
Changed foreach Enumeration to Linq.SUM
=> Git gub contributors

OurUmbraco.Site/Views/Partials/Home/GitHubContributors.cshtml, OurUmbraco/Community/Controllers/GitHubContributorController.cs, OurUmbraco/Community/Controllers/GitHubGlobalContributorModel.cs, OurUmbraco/Community/Models/GitHubContributorsModel.cs
Write contributors to json file and use file cached value with help from @abjerner 👍
=> Write contributors to json file and use file cached disk value

OurUmbraco.Site/Views/Master.cshtml, OurUmbraco.Site/Views/Partials/Projects/ProjectDetails.cshtml, OurUmbraco.Site/Views/Project.cshtml
Issue: http://issues.umbraco.org/issue/OUR-451
I have updated Fancybox to v3 http://fancyapps.com/fancybox/3/, which is optimized for mobile and touch devices.
=> Update to FancyBox v3

OurUmbraco.Site/Views/Master.cshtml, OurUmbraco.Site/Views/Project.cshtml
Just an update to latest Fancybox v3.
It fix the hotkey for fullscreen and also works better with the lorem ipsum images locally.
=> Update Fancybox to latest v3

OurUmbraco.Site/config/MeetupUmbracoGroups.txt
(as posted by @camaya on the community Slack)
=> Added the new Barcelona user group

OurUmbraco.Client/src/scss/pages/_forum.scss
Fixing alignment on sign in and new topic buttons in Forum
=> Updated padding on green buttons

OurUmbraco.Site/Views/FileDownload.cshtml
fix for this issue - http://issues.umbraco.org/issue/OUR-483
=> fix txt files downloading

OurUmbraco.Site/Views/Partials/Project/Edit.cshtml, OurUmbraco/Our/Controllers/ProjectController.cs
Fixes
- [OUR-480 MIT License - default to "cool URL"](http://issues.umbraco.org/issue/OUR-480)
Also updated some old references to codeplex.com, replaced with gthub.com & bitbucket.org
=> Create Project: Updated default MIT license URL

OurUmbraco.Site/OurUmbraco.Site.csproj, OurUmbraco.Site/Views/Partials/Community/Home.cshtml, OurUmbraco.Site/config/CommunityBlogs.json, OurUmbraco/Community/BlogPosts/BlogCachedRssItem.cs, OurUmbraco/Community/BlogPosts/BlogInfo.cs, OurUmbraco/Community/BlogPosts/BlogPostsService.cs, OurUmbraco/Community/BlogPosts/BlogRssChannel.cs, OurUmbraco/Community/BlogPosts/BlogRssItem.cs, OurUmbraco/Community/BlogPosts/BlogRssUtils.cs, OurUmbraco/NotificationsCore/Notifications/ScheduleHangfireJobs.cs, OurUmbraco/Our/GoogleOAuth/UmbracoStandardOwinStartup.cs, OurUmbraco/OurUmbraco.csproj
- Information about the community blogs are stored in `/OurUmbraco.Site/config/CommunityBlogs.json`
- Blog posts are cached to `/OurUmbraco.Site/App_Data/TEMP/CommunityBlogPosts.json`
- Hangfire *should* update the JSON file every hour, but this probably needs some testing to confirm it's actually happening
- "Blog Posts" section lists the most recent blog post of each community blog
=> Another section for the Community page: Blog posts

OurUmbraco.Site/Views/Download.cshtml
Removes the video overlay until we have a more appropriate video about Cloud & use's Sofie's awesome animated gifs & link to a doc page
=> Update to download page with ani.gif

OurUmbraco.Site/Views/Partials/Community/MVPs.cshtml
Based on on suggestion from this issue:
http://issues.umbraco.org/issue/OUR-455#u=1497105524778
Probably still a bit work in progress. I'll look forward to any feedback ;)
=> Updated the MVPs list a bit

OurUmbraco.Site/Views/Partials/Community/Videos.cshtml, OurUmbraco.Site/config/YouTubePlaylists.json
Adds uHangout YouTube playlist to the community videos
=> uHangout Video PR

OurUmbraco.Client/src/scss/elements/_videos.scss, OurUmbraco/Community/Videos/CommunityVideosService.cs
The stuff I've found for now ;)
=> Various improvements to videos

OurUmbraco.Site/config/IISRewriteMaps.config
For: 
* Add-ons/UmbracoCourier/Index + all sites under
* Umbraco-Cloud - config transforms
=> Adding rewrites

OurUmbraco.Site/Views/Partials/Community/Gitter.cshtml
As the link is external, it should probably open in a new tab/window
=> Open "Join the discussion on Gitter" in a new tab/window

OurUmbraco.Site/Views/Partials/Community/Map.cshtml, OurUmbraco.Site/Views/Partials/Members/Profile.cshtml, OurUmbraco/Community/Map/MapEventHandler.cs, OurUmbraco/Community/Map/RadarHangfireJobs.cs, OurUmbraco/Our/GoogleOAuth/UmbracoStandardOwinStartup.cs, OurUmbraco/OurUmbraco.csproj, OurUmbraco/packages.config
* Adds 3rd Party Hangfire.Console library - https://github.com/pieceofsummer/Hangfire.Console
* New Examine Field added to indicate if the field 'location' exists & has a value set (allows us to find these members with Examine query)
* Adds new Hangfire Job that queries Examine for members missing lat/lon but has legacy free textfield Location field & attempts to look them up with Google Geo API
=> Radar - bleep bloop beep

OurUmbraco.Site/Views/Partials/Community/Map.cshtml
CSS update suggestion from Bjarne in the issue #212
=> Fixes #212 - Fixes Avatars Under the Map

OurUmbraco.Site/Views/Master.cshtml
Swapped the "Send pageview" and "Set dimension" statement. You should always first set the dimension and then send the pageview. I did it the other way around.
=> Some Google Analytics changes

OurUmbraco.Site/config/MeetupUmbracoGroups.txt
This is my first crack at a Pull Request so I hope I got this right!
=> Update Umbraco Groups with Surrey Umbraco Meetup

OurUmbraco.Client/src/scss/sections/_gitter.scss
Spacing seemed a little off and looked like it could do with some minor improvements to just improve readability.
=> Tidy the homepage gitter title/paragraph

OurUmbraco.Site/Views/Partials/Members/ResetPassword.cshtml
=> Added a link to the log in form after a reset password

OurUmbraco.Client/src/scss/sections/_docs.scss
As per https://github.com/umbraco/UmbracoDocs/issues/980
=> Adding custom markdown classes for documentation

OurUmbraco.Site/config/IISRewriteMaps.config
I've updated the documentation about the licensing model we use for our products, e.g. Courier and Forms.
Need this rewrite, as I've deleted the old article about the same.
See: https://github.com/umbraco/UmbracoDocs/pull/1240
=> Rewrite to new licensing model article

OurUmbraco.Site/config/YouTubePlaylists.json
Video about Tour Umbraco Back Office for user thats speak Spanish...
Im start a blog about Umbraco in spanish language.
grettings!!!
=> Video Umbraco in Spanish

LICENSE.md
Add MIT License since most of the repos follow MIT License.
=> LICENSE.md: Add MIT License file

OurUmbraco.Site/config/IISRewriteMaps.config
see https://github.com/umbraco/UmbracoDocs/pull/930 for ref
=> Add rewrite for deleted courier docs

OurUmbraco.Client/src/scss/elements/_sidebar.scss, OurUmbraco.Site/Views/Partials/Projects/ListCategories.cshtml, OurUmbraco.Site/Views/Partials/Projects/ListProjects.cshtml, OurUmbraco.Site/Views/Projects.cshtml
1. added active state of current level 2  menu item added 
2. fixed header for latest packages
https://github.com/umbraco/OurUmbraco/issues/298
=> fixes #298

OurUmbraco.Site/Views/Download.cshtml
Adds a bit of information regarding V8 nightly builds.
=> Add info regarding V8 nightly

OurUmbraco.Site/Views/Master.cshtml
Yahoo pipes does not exist anymore, let's save bandwith :-)
=> Remove Yahoo Pipes from master.cshtml

OurUmbraco.Site/Views/Dashboard.cshtml
Added a filter for switching between issues and pull request. And option to filter on repository
=> Dashboard filters

OurUmbraco/Documentation/DocumentationUpdater.cs
PR with folder not ready yet, btw.
=> Ignore Old Courier version folder in menustructure

OurUmbraco.Site/config/IISRewriteMaps.config
NOTE: This is pending PR on the Documentation repo !!!
=> Add rewrites for Courier documentation

OurUmbraco/Documentation/DocumentationUpdater.cs
New folders were added in https://github.com/umbraco/UmbracoDocs/pull/1534 for now this PR will sort them correctly in the menu
=> Reorder menu for https://github.com/umbraco/UmbracoDocs/pull/1534

OurUmbraco.Client/src/scss/elements/_header.scss, OurUmbraco.Client/src/scss/elements/_member.scss, OurUmbraco.Client/src/scss/elements/_sidebar.scss
Fixed issue with mobile navigation been white on white until the sticky bar appears. 
Fixed navigation levels header tags to be white on the mobile blue backgrounds.
Changed the green solved to the blue on the member profile.
=> CSS updates fixing issues on mobile and member profile

OurUmbraco.Site/config/CommunityBlogs.json
Add Moriyama blog to community blogs
=> Add Moriyama blog

OurUmbraco.Client/src/scss/sections/_docs.scss, OurUmbraco.Site/Views/Partials/Documentation/DisplayMarkdown.cshtml
This is a first attempt to address [UmbracoDocs #1665](https://github.com/umbraco/UmbracoDocs/issues/1665).
Since I don't have a way to build the site and test, this is just a draft PR for anyone to comment on and discuss, since I don't know if this will be "enough" - @jmayntzhusen [seemed to imply](https://github.com/umbraco/UmbracoDocs/issues/1665#issuecomment-481580006) that there was more to it than the changes included in this draft PR.
fixes https://github.com/umbraco/UmbracoDocs/issues/1665
=> Highlight selected docs version

OurUmbraco.Site/config/CommunityBlogs.json
Added blog as entry to CommunityBlogs.json
=> Added blog - jvantroyen

OurUmbraco.Site/Views/Partials/Members/ForgotPassword.cshtml, OurUmbraco.Site/Views/Partials/Members/Login.cshtml, OurUmbraco.Site/Views/Partials/Members/ResetPassword.cshtml, OurUmbraco/MarketPlace/NodeListing/NodeListingProvider.cs
I think this could be a potential fix to issue #401. I say potential as I am unable to test this locally. But going through the conversation @bjarnef on the issue and the fact that one person experiences it while other doesn't makes me think so.
=> 401 : Null check contributed packages pages

OurUmbraco.Client/src/scss/elements/_package-detail.scss, OurUmbraco.Site/Views/Partials/Projects/ProjectDetails.cshtml
Hi,
This PR fixes issue number 354. The package details page must show the available badges. Let me know if it looks okay. 
Poornima
=> Package Details Page: Show the creator's badges under their profile picture

OurUmbraco.Site/OurUmbraco.Site.csproj, OurUmbraco.Site/Views/CommunityHubUProfileBlogPosts.cshtml, OurUmbraco/Community/BlogPosts/BlogPostsService.cs, OurUmbraco/Community/BlogPosts/BlogRssItem.cs, OurUmbraco/Community/Controllers/CommunityHubPageController.cs, OurUmbraco/Community/Models/ViewModels/CommunityBlogPostViewModel.cs, OurUmbraco/Our/MigrationsHandler.cs, OurUmbraco/OurUmbraco.csproj
This PR adds an addtional template to Community Hub Page. When used, the page will show a feed of uProfile blog posts.
=> Add uProfile blog post page

OurUmbraco.Site/Views/Partials/SearchResults.cshtml
A placeholder text to the search input on the search pages has been added as suggested. 
https://github.com/umbraco/OurUmbraco/issues/444
=> Add placeholder text to search input on search page

OurUmbraco.Site/Views/Download.cshtml
Lars doesn't want the parameters anymore.
=> Update link to umbraco.com

OurUmbraco/Community/GitHub/GitHubService.cs
Adding RFC and organisers repo to github service.
Is there any others that should be included in contributions?
=> Adding other repos

OurUmbraco.Client/src/scss/elements/_sidebar.scss
=> fix(sidebar): fix height issue

OurUmbraco.Site/config/IISRewriteMaps.config
This rewrite is dependent on https://github.com/umbraco/UmbracoDocs/pull/2035
=> Docs package section rewrite rules

OurUmbraco.Site/web.vsts.config
Adds our.umbraco.local as an ignore rule for the HTTPS redirect/rewrite in web.config
=> Adds our.umbraco.local

OurUmbraco.Site/config/MeetupUmbracoGroups.txt
Added Thames Valley Umbraco User Group to list
=> Added new meetup group

OurUmbraco.Site/config/IISRewriteMaps.config
Based on the broken link report here: https://github.com/umbraco/UmbracoDocs/issues/2101
=> Rewrite link found on google to correct article

OurUmbraco.Site/config/IISRewriteMaps.config
Add rewrite to link to the article with the same content.
=> Rewrite: Removing article with duplicate content

OurUmbraco.Site/Views/Partials/Projects/ProjectDetails.cshtml
To please my eyes, I changed the casing for _NuGet_, _Our_ and _.NET_ 😄
=> Changed text casing in project details

OurUmbraco/MarketPlace/NodeListing/NodeListingProvider.cs
Fix for issue here:
https://github.com/umbraco/Umbraco.Packages/issues/31
Previously showing -1 when no Karma. Now showing 0 as expected, see screenshot:
=> updating logic for showing Karma on a package to work when no karma yet

OurUmbraco.Site/Views/Partials/Project/EditFiles.cshtml, OurUmbraco/MarketPlace/NodeListing/NodeListingProvider.cs
As per packages issue: https://github.com/umbraco/Umbraco.Packages/issues/55
Before:
After:
=> Packages version list

OurUmbraco/Documentation/DocumentationUpdater.cs
Adding Heartcore and ordering the nav in a more logical order
=> Update to Documentation ordering

OurUmbraco.Site/config/githubhq.txt
=> More HQ people

OurUmbraco/Project/Api/ProjectUploadController.cs
Reverts umbraco/OurUmbraco#590
=> Revert "Grabs pkg version from form and updates the content node accordingly"

OurUmbraco/Project/Api/ProjectUploadController.cs
This will work with https://github.com/umbraco/UmbPack/pull/28 to enable UmbPack to archive specific package files.
=> Add archive endpoint for UmbPack

OurUmbraco.Client/src/scss/core/_bootstrap.scss, OurUmbraco.Client/src/scss/core/_variables.scss, OurUmbraco.Client/src/scss/elements/_container.scss, OurUmbraco.Client/src/scss/elements/_footer.scss, OurUmbraco.Client/src/scss/mixins/_responsiveness.scss, OurUmbraco.Client/src/scss/style.scss, OurUmbraco.Site/Views/Master.cshtml
This changes the footer from being a black box to match our actual brand colours.
**Old**
**New**
=> Update footer theme

OurUmbraco.Site/config/CommunityBlogs.json
I recently started blogging again. So added my new blog
=> Added my blog

OurUmbraco.Site/config/CommunityBlogs.json
it's no longer possible to find your member id from the 'view my public profile' link?
=> Add too orangey for crows to the list of community umbraco blogs

OurUmbraco.Site/config/YouTubePlaylists.json
Added my youtube playlist of around 30 Umbraco videos.
They are mainly practical ways of doing things e.g. setting up Umbraco on Azure via Devops with Code Examples.
Note: I had to unlink my OurUmbraco account from github to expose my OurUmbraco member id - as i see only numbers are accepted in the YouTubePlaylists.json config file - you might want to update your integration guidelines here
https://our.umbraco.com/community/community-videos/how-do-i-add-my-own-videos/
Thanks.
=> Added John Blair's Youtube Playlist of Umbraco Videos.

OurUmbraco.Site/Views/Partials/Members/QuickMenu.cshtml
Added a packages link to the quick menu
Fixes #635 
Fixes https://github.com/umbraco/Umbraco.Packages/issues/65
=> 633 Link to packages from the profile window

OurUmbraco.Site/config/IISRewriteMaps.config
Ref: https://github.com/umbraco/UmbracoDocs/pull/2772
=> Rewrite for Cloud articles

OurUmbraco.Client/gulpfile.js
=> Refactor gulp file

OurUmbraco.Client/src/scss/elements/_search-results.scss, OurUmbraco.Site/Views/Partials/SearchResults.cshtml, OurUmbraco/Our/Models/SearchResultBreadcrumbModel.cs, OurUmbraco/Our/SearchResultExtensions.cs, OurUmbraco/OurUmbraco.csproj
Added breadcrumbs to the search results with links to the relevant pages
resolves #452
=> 452 Add breadcrumb to the search result entries

OurUmbraco.Site/Views/ReleaseCompare.cshtml
Added the missing latest release menu item
resolves #545
=> 545 Lastest release menu item dissapears on compare versions

OurUmbraco.Site/Views/Release.cshtml
Added red text which is shown if not on latest version with a link to the newer version
resolves #604
=> 604 If a user isn't on the latest relase page, make it more obvious

OurUmbraco.Site/config/IISRewriteMaps.config
https://github.com/umbraco/UmbracoDocs/pull/2934
=> Added rewrite for moving latch folder to hostname folder

OurUmbraco.Site/config/CommunityBlogs.json
Added my blog RSS feed for Our Blogs
=> Add Rick Butterfield blog to `CommunityBlogs.json`

OurUmbraco.Site/config/CommunityBlogs.json
Just updating the config with new details of my blog and media location for the RSS feed.
=> Update to Blog url and media location

OurUmbraco/Documentation/DocumentationUpdater.cs
**This PR is dependant on
This Docs PR: https://github.com/umbraco/UmbracoDocs/pull/3092
This Our PR: https://github.com/umbraco/OurUmbraco/pull/693**
Also added a new one for the new Getting Started section.
=> Updating current switches

OurUmbraco.Site/config/IISRewriteMaps.config
The IIS (v9) article has been moved from the Server Setup section to the Install section.
Adding a rewrite here, to accommodate this move.
=> Rewrite for moved article

OurUmbraco.Site/web.vsts.config
This change needs to be merged in on Tuesday morning for when we release umbraco 9
=> Updated the CurrentMajorVersion so it is 9

OurUmbraco.Site/Views/Download.cshtml
Added new requirements and recommendations.
=> Update for v9

OurUmbraco.Site/config/githubhq.txt
Ronald is showing up high on the number of commits this year on our.umb homepage.
Saw he was missing from this file and added his GitHub username @nul800sebastiaan
=> Adds Ronald Barendse

OurUmbraco.Site/config/CommunityBlogs.json
This adds my newly started dev.to blog 😄 ✏️
=> Adds Nikolajs blog

OurUmbraco.Site/config/CommunityBlogs.json
Added my blog to the community RSS
=> Added Enkel Media Blog to RSS

OurUmbraco/Documentation/DocumentationUpdater.cs
Reverts umbraco/OurUmbraco#756
=> Revert "Updated navigation menu for Reference section"

OurUmbraco.Site/config/IISRewriteMaps.config
rewriting from deploy setting in the cloud section to the deploy settings in the addons section.
=> Added rewrite for deploy settings

OurUmbraco.Site/Views/DocumentationSubpage.cshtml, OurUmbraco.Site/Views/Partials/SearchResults.cshtml, OurUmbraco.Site/web.vsts.config, OurUmbraco/Our/Examine/OurSearcher.cs
I've run and tested all these changes locally.
For some reason though, I cannot push my branch from my machine to Github.
I get the following message when trying: (using GitBash)
```
$ git push --set-upstream origin v10/DocsLaunch
remote: Permission to umbraco/OurUmbraco.git denied to sofietoft.
fatal: unable to access 'https://github.com/umbraco/OurUmbraco.git/': The requested URL returned error: 403
```
The changes in this PR, are made directly here on the GitHub repo, and they are identical to the ones I've made on my local Our.
**This PR needs to be merged next week - Wednesday, June 15th at the latest.**
=> v10: Prepare Our for v10 docs

OurUmbraco.Client/src/js/app.js, OurUmbraco.Client/src/scss/elements/_breadcrumb.scss, OurUmbraco.Client/src/scss/elements/_sidebar.scss, OurUmbraco.Site/Views/Partials/Documentation/Navigation.cshtml
List bullets have been removed (css)
As part of improving the user experience for navigation on smaller devices I have made the breadcrumb trail visible in advance of making the navigation collapsable.
=> Breadcrumb and Menu UX improvements

OurUmbraco.Site/Views/Partials/Community/Home.cshtml
BTW I know this isn't a Hacktoberfest repo. Am just sending this as I noticed it. Definitely not a Hacktoberfest worthy PR 😆
=> fix incorrect wording

OurUmbraco.Site/Views/Projects.cshtml
Add marketplace banner to package section
=> Update Projects.cshtml with marketplace banner

OurUmbraco.Site/config/CommunityBlogs.json
My blog changed from rickbutterfield.com to rickbutterfield.dev and I hadn't updated this!
=> Update URL for Rick Butterfield blog

OurUmbraco.Site/Views/Partials/Members/Profile.cshtml, OurUmbraco/Our/Controllers/ProfileController.cs
Added a Twitter alias field to the profile edit form so members can change their Twitter handle
=> Enabled Twitter handle changes

OurUmbraco.Site/config/GitHubPublicRepositories.json, OurUmbraco/Community/GitHub/GitHubService.cs
Added new [Umbraco.CMS.Backoffice](https://github.com/umbraco/Umbraco.CMS.Backoffice) repository.
=> Add Umbraco.CMS.Backoffice

OurUmbraco.Site/config/CommunityBlogs.json
Added my personal blog site johanreitsma.com with the required settings.
=> Update CommunityBlogs.json to add JohanReitsma.com

OurUmbraco.Site/Views/Release.cshtml
Updated the links to the installation and upgrading docs so they now point at the new docs site
=> Updated out of date docs links

OurUmbraco.Site/config/CommunityBlogs.json
I am in the process of rebuilding/moving my blog and I have not had time to create an RSS feed yet. And I dont know when I will have the time so until then I will remove myself from this feed.
Will add myself again once I have added a rss. :)
=> Remove Adolfi.dev from CommunityBlogs

OurUmbraco.Site/config/CommunityBlogs.json
Proper content will be appearing here soon, promise!
=> Add my blog url

OurUmbraco.Site/config/CommunityBlogs.json
=> Added my blog (harrygordon.co.uk) to the blog list

OurUmbraco.Site/config/CommunityBlogs.json
=> Updated blog URL
